# Site Settings
name: dustyfloor
title: dustyfloor
description: 게임 만들고 게임 하는 사람
tags:
  - TIL
  - Unity
  - Python
  - Steam
  - Review
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  #- title: Category
  #  url: /category 
  #태그가 있는데 카테고리가 굳이 또 필요할까? 일단 지워놓자
  - title: Tags
    url: /tags
email: 

# Social Media Settings
# Remove the item if you don't need it
github_username: dustyfloor
twitter_username: dustyfloor_
disqus_username: disqus_username

# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dustyfloor.github.io" # the base hostname & protocol for your site
google_analytics: "G-DN9EBTLMJ8"
language: "ko"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - wdm
  - jekyll-sitemap

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
#version: v3.1.1
